---
- name: Cleaning Up
  block:
  - service:
      name: docker
      state: stopped
  - file:
      path: /var/lib/docker
      state: absent
  tags:
    - never

- name: Include distribuition specific variables
  include_vars: "{{ ansible_distribution | lower }}.yml"

- name: Install pip and dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ pip_packages }}"

- name: Upgrade pip
  pip:
    name: pip
    state: latest

- name: Install docker pip package
  pip:
    name: "docker"
    state: "latest"

- name: Remove Docker old versions
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ docker_old_packages }}"

- name: Install Docker repository
  get_url:
    url: 'https://download.docker.com/linux/centos/docker-ce.repo'
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution | lower == 'centos' 

- name: Install Docker engine
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_packages }}"

- name: Install Docker SNI dependencies
  pip:
    name: "{{ pip_docker_sni }}"
    state: "present"

- name: Creating docker user
  user: 
    name: docker
    groups: "docker"
    append: true

- name: Enable docker service
  service:
    name: docker
    enabled: true
    state: started

- include: swarm.yml
- include: tunning.yml