---
- name: Include distribuition specific variables
  include_vars: "{{ ansible_distribution | lower }}.yml"

- name: Creating docker user
  user: name=docker

- name: Install pip and dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ pip_packages }}"

- name: Install docker-py pip package
  pip:
    name: "docker-py"
    state: "present"

- name: Install Docker stable community edition
  package:
    name: "{{ }}"

- include: tunning.yml