---
- name: Enable ports on firewall
  block:
  - name: Enable cluster management communication TCP port
    firewalld:
      port: "{{ docker_swarm_port }}/tcp"
      permanent: yes
      state: enabled
  - name: Enable node communication TCP port
    firewalld:
      port: 7946/tcp
      permanent: yes
      state: enabled
  - name: Enable node communication UDP port
    firewalld:
      port: 7946/udp
      permanent: yes
      state: enabled
  - name: Enable overlay network UDP port
    firewalld:
      port: 4789/udp
      permanent: yes
      state: enabled
  - command: firewall-cmd --reload

- name: Enable Docker swarm mode
  docker_swarm:
    state: present
    advertise_addr: "{{ docker_swarm_addr }}"
  when: "inventory_hostname == groups['integr8-docker-swarm-manager'][0]"
  register: swarm_info

- name: Declare facts of first manager
  set_fact:
    manager_token: "{{ swarm_info.swarm_facts.JoinTokens.Manager }}"
    worker_token: "{{ swarm_info.swarm_facts.JoinTokens.Worker }}"
    docker_manager_address: "{{ docker_swarm_addr }}:{{ docker_swarm_port }}"
  when: "inventory_hostname == groups['integr8-docker-swarm-manager'][0]"

- name: Distribute the facts
  set_fact:
    manager_token: "{{hostvars[groups['integr8-docker-swarm-manager'][0]]['manager_token'] }}"
    worker_token: "{{hostvars[groups['integr8-docker-swarm-manager'][0]]['worker_token'] }}"
    docker_manager_address: "{{hostvars[groups['integr8-docker-swarm-manager'][0]]['docker_manager_address'] }}"
  when: "inventory_hostname != groups['integr8-docker-swarm-manager'][0]"

- name: Check if "Swarm Mode" is enabled
  shell: docker info
  changed_when: False
  register: docker_info

- name: Enable node as Worker
  shell: "docker swarm join --token {{ worker_token }} {{ docker_manager_address }}"
  when: "inventory_hostname != groups['integr8-docker-swarm-manager'][0]
    and docker_info.stdout.find('Swarm: active') == -1"

- name: Create a Docker Swarm network
  docker_network:
    name: "{{ docker_swarm_network_name }}"
    driver: overlay
    driver_options:
      com.docker.network.bridge.enable_icc: "false"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.name: "{{ docker_swarm_network_name }}"
      com.docker.network.enable_ipv6: "true"
    ipam_options:
      subnet: "{{ docker_swarm_network }}"
      gateway: "{{ docker_swarm_network | ipaddr('net') | ipaddr('1') | ipaddr('ip') }}"
  when: docker_swarm_network is defined and docker_swarm_network | ipaddr('net') and inventory_hostname == groups['integr8-docker-swarm-manager'][0]